# Generated by Django 3.2.25 on 2025-08-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the menu category (e.g., 'Appetizers', 'Desserts').", max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The display name of the restaurant (e.g., 'Vrindavan Sweets').", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text="Unique URL-friendly identifier for the restaurant's menu page.", max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, help_text="Upload the restaurant's logo image.", null=True, upload_to='restaurant_logos/')),
                ('contact_info', models.TextField(blank=True, help_text='Contact details for the restaurant (e.g., address, phone).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the restaurant profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the restaurant profile was last updated.')),
                ('user', models.OneToOneField(help_text='The user account associated with this restaurant.', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the menu item (e.g., 'Paneer Butter Masala').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='A short description of the menu item.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu item.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the menu item.', null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True, help_text='Check if the item is currently available.')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to mark this item as featured (e.g., for a carousel).')),
                ('is_special', models.BooleanField(default=False, help_text="Check to mark this item as a 'Today's Special'.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the menu item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the menu item was last updated.')),
                ('category', models.ForeignKey(blank=True, help_text='The category this menu item belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.category')),
                ('restaurant', models.ForeignKey(help_text='The restaurant this menu item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this category belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'name')},
        ),
    ]
